### PR TITLE
Woothee 1.7

### PR DESCRIPTION
**Pull request by hhatto**
* update current dataset and testsets
* Support curl (woothee/woothee/pull/30)
* Support trendictionbot crawler (woothee/woothee/pull/37)
* Support Yeti 1.1 (woothee/woothee/pull/36)

### CODE REVIEW

**Comment by tagomoris** [comment]
LGTM. Thank you!

**Comment by tagomoris** [comment]
@hhatto are you interested in maintaining this implementation?

**Comment by hhatto** [comment]
> @hhatto are you interested in maintaining this implementation?

Yes!! 😄

**Comment by tagomoris** [comment]
I invited you to woothee-go-team. Enjoy! :D

**Comment by hhatto** [comment]
Thank you very much!!

**Comment by tell-k** [comment]
@hhatto @tagomoris   

Welcome to the woothee team :)

@hhatto is the author of [woothee-rust](https://github.com/hhatto/woothee-rust).
Just a good opportunity, I suggest that we ask him to move "woothee-rust" to this organizaition.

How do you feel about this?

thx.

**Comment by hhatto** [comment]
> Just a good opportunity, I suggest that we ask him to move "woothee-rust" to this organizaition.
> 
> How do you feel about this?

@tell-k 
Thanks for your suggestion.
If there is no problem as "Woothee Project", I am very much appreciated for this suggestion.
woothee-rust has already followed the latest version of woothee.

**Comment by tagomoris** [comment]
It sounds great idea.
@hhatto I granted your role to Owner, to be able to transfer repositories to this organization!

**Comment by hhatto** [comment]
> I granted your role to Owner, to be able to transfer repositories to this organization!

Thanks. done 😄 

https://github.com/woothee/woothee-rust

**Pull request merged**
